# name: Publish

# on:
#   release:
#     types: [published]

# jobs:
#   build:
#     name: Build, Lint, Test, and Publish

#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         node: ["14.x", "16.x", "18.x"]
#         os: [ubuntu-latest]

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node }}
#           cache: "npm"
#           registry-url: https://registry.npmjs.org/

#       - name: Install dependencies
#         run: npm install

#       - name: Prettier
#         run: npm run format

#       - name: Eslint
#         run: npm run eslint

#       - name: Test
#         run: npm run test

#       - name: Build
#         run: npm run build

#       # This step is a work in progress, until further notice, prefer to use
#       # `./publish.sh` from your local machine. This is possible from either
#       # the `main` or `master` branches of the repository (a.k.a. the default
#       # branch); Which should be stable due to other existing workflows.
#       - name: Publish
#         run: npm publish
