name: Callable Build Distribution Workflow

on: [workflow_call]

jobs:
  distribution:
    name: Build Distribution (${{ matrix.os }} - ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["20"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Create "dist/" Folder Contents
        run: pnpm build

      - name: Create Package
        run: npm pack
