name: Callable Build Distribution Workflow

on: [workflow_call]

jobs:
  distribution:
    name: Build Distribution (${{ matrix.os }} - ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16.14"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Create "dist/" Folder Contents
        run: npm run build

      - name: Create Package
        run: npm pack
