name: Callable Essential Test Workflow

on: [workflow_call]

jobs:
  test:
    name: Essential (${{ matrix.os }}, ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["20"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Scan Vulnerabilities
        run: npm audit --production

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm eslint

      - name: Test Unit
        run: pnpm test:ci
