name: Publish

on:
  # Type 'published' triggers if the release is published, no matter it's draft or not.
  # Type 'created' triggers when a NON-draft release is created AND published.
  push:
    tags:
      - "v*.*.*"
  release:
    types: [created]

jobs:
  essential-test:
    name: Call Essential Test Workflow
    uses: ./.github/workflows/essential-test.yml

  build-publishable-distribution:
    name: Publish
    needs: [essential]

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
          scope: "@owner-or-organization"

      - name: Install dependencies
        run: pnpm install

      - name: Build Distribution
        run: pnpm build

      - name: Publish
        run: npm publish
        env:
          # https://docs.github.com/en/enterprise-server@3.3/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
