name: Publish

on:
  # Type 'published' triggers if the release is published, no matter it's draft or not.
  # Type 'created' triggers when a NON-draft release is created AND published.
  push:
    tags:
      - "v*.*.*"
  release:
    types: [created]

jobs:
  essential-test:
    name: Call Essential Test Workflow
    uses: ./.github/workflows/essential-test.yml

  build-publishable-distribution:
    name: Publish
    needs: [essential]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.14"
          cache: "npm"
          registry-url: https://npm.pkg.github.com/
          scope: "@franciscokloganb"

      - name: Install dependencies
        run: npm install

      - name: Build Distribution
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          # https://docs.github.com/en/enterprise-server@3.3/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
